<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- definition of elements -->
  <xs:element name="Title" type="xs:string"/>
  <xs:element name="ID" type="xs:int"/>
  <xs:element name="Intitule" type="xs:string"/>
  <xs:element name="Text" type ="xs:string"/>

  <!-- schema -->
  <xs:element name="Tutorial">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref ="Title"/>
        <xs:element name="Step" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="ID"/>
              <xs:element ref="Intitule"/>
              <xs:element ref="Text"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>